version: '3.8'

services:
  app:
    container_name: ${PROJECT_NAME}_service
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app:rw,cached
      - ./.env:/app/.env
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - db
  db:
    container_name: ${PROJECT_NAME}_db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DBNAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: 'Europe/Moscow'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    restart: always

volumes:
  postgres_data:
